kalina/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schetovodstvo.urls', namespace='schetovodstvo')),
]

schetovodstvo/urls.py
from django.urls import path
from . import views

app_name = 'schetovodstvo'

urlpatterns = [
path('', views.index, name='index'),
path('catalog.html', views.oborotna_vedomost, name='oborotna_vedomost'),
path('upload.html', views.upload_file_prodajbi, name='upload_file_prodajbi'),
path('upload_pok.html', views.upload_file_pokupki, name='upload_file_pokupki'),
path('display.html', views.function_display, name='function_display'),
path('upload_zaplati.html', views.upload_file_zaplati, name='upload_file_zaplati'),
path('upload_bank.html', views.upload_file_bank, name='upload_file_bank'),
]

schetovodstvo/models.py
from django.db import models

# Create your models here.
class smetkoplan(models.Model):
        smetka=models.IntegerField(null=True, blank=True)
        opisanie=models.CharField(max_length=100, null=True, blank=True)
        n_saldo_dt=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
        n_saldo_kt=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
        k_saldo_dt=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
        k_saldo_kt=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
        spare=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)


        
class vedomost(models.Model):
        first_f=models.CharField(max_length=100, null=True, blank=True)
        doc=models.CharField(max_length=100, null=True, blank=True)
        date=models.CharField(max_length=100, null=True, blank=True)
        nomer=models.CharField(max_length=100, null=True, blank=True)
        firma=models.CharField(max_length=100, null=True, blank=True)
        buls=models.CharField(max_length=100, null=True, blank=True)
        opisanie=models.TextField( null=True, blank=True)
        suma=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
        debit=models.IntegerField(null=True, blank=True)
        credit=models.IntegerField(null=True, blank=True)

        def __str__(self):
                return self.first_f

schetovodstvo/forms.py
from django import forms
from .models import vedomost

class UploadFileForm(forms.Form):
    file = forms.FileField()

class criterii_filtar(forms.Form):
    DOCUMENT_CHOICES = [
        ('',''),
        ('фактура','фактура'),
        ('отчет за продажбите','отчет за продажбите'),
        ('ведомост за заплати','ведомост за заплати'),
        ('банково извлечение', 'банково извлечение')
        ]

    crit1=forms.CharField(required=False,label='Търсене в описание')
    crit2=forms.CharField(required=False,label='Проверка на сметка Дт-Кт')

    crit3=forms.ChoiceField(required=False,
                            label='Търсене по вид документ',
                            choices=DOCUMENT_CHOICES,
                            widget=forms.Select(attrs={'class': 'form-select'})
                            )
    crit4=forms.CharField(required=False,label='Търсене по месец - 202501')
class vedomost_form(forms.ModelForm):
    class Meta:
        model = vedomost
        fields = ['first_f','doc','date','firma','opisanie', 'suma', 'debit', 'credit']
        widgets = { 'first_f': forms.DateInput(attrs={'size': 8}),
                    'opisanie': forms.TextInput(attrs={'size': 40}),
                   'debit': forms.NumberInput(attrs={'size': 5}),
                   'credit': forms.NumberInput(attrs={'size': 5}),
                   'date': forms.DateInput(attrs={'size': 8}),


                   }

schetovodstvo/views.py
from django.shortcuts import render
from .models import vedomost, smetkoplan
from .forms import UploadFileForm,criterii_filtar, vedomost_form 
import csv
import io
from django.forms import modelformset_factory
from django.db.models import Q
# Create your views here.


class Sm:
    def __init__(self,smetka,s_ime, dt, kt,odt,okt):
        self.smetka=smetka
        self.s_ime=s_ime
        self.n_debit=float(dt)
        self.n_kredit=float(kt)
        self.debit=float(odt)
        self.kredit=float(okt)
#        self.s_debit=float(s_dt)
#        self.s_kredit=float(s_kt)
        if (self.n_debit+self.debit)-(self.n_kredit+self.kredit)>0:
            self.s_debit=float(self.n_debit+self.debit-self.n_kredit-self.kredit)
            self.s_kredit=0
        elif (self.n_kredit+self.kredit)-(self.n_debit+self.debit)>0:
            self.s_debit=0
            self.s_kredit=float(self.n_kredit+self.kredit-self.n_debit-self.debit)
        else:
            self.s_debit=0
            self.s_kredit=0

def smetkoplan_analiz(xxx, smetkoplan_obj):
    for row in xxx: # за всеки ред от таблицата, която съдържа осчетоводените операции
            for key in smetkoplan_obj: # за всеки ключ от речника smetkoplan_obj
                if row.debit==smetkoplan_obj[key].smetka: # ако стойността в колоната debit на таблицата е равна на стойността на ключа smetka 
                    smetkoplan_obj[key].debit+=float(row.suma)
                    if (smetkoplan_obj[key].n_debit+smetkoplan_obj[key].debit)-(smetkoplan_obj[key].n_kredit+smetkoplan_obj[key].kredit)>0:
                        smetkoplan_obj[key].s_debit=float(smetkoplan_obj[key].n_debit+smetkoplan_obj[key].debit-smetkoplan_obj[key].n_kredit-smetkoplan_obj[key].kredit)
                        smetkoplan_obj[key].s_kredit=0
                    elif (smetkoplan_obj[key].n_kredit+smetkoplan_obj[key].kredit)-(smetkoplan_obj[key].n_debit+smetkoplan_obj[key].debit)>0:
                        smetkoplan_obj[key].s_debit=0
                        smetkoplan_obj[key].s_kredit=float(smetkoplan_obj[key].n_kredit+smetkoplan_obj[key].kredit-smetkoplan_obj[key].n_debit-smetkoplan_obj[key].debit)

#                    smetkoplan_obj[key].s_debit+=float(row.suma)
                if row.credit==smetkoplan_obj[key].smetka: # ако стойността в колоната debit на таблицата е равна на стойността на ключа smetka 
                    smetkoplan_obj[key].kredit+=float(row.suma)
                    if (smetkoplan_obj[key].n_debit+smetkoplan_obj[key].debit)-(smetkoplan_obj[key].n_kredit+smetkoplan_obj[key].kredit)>0:
                        smetkoplan_obj[key].s_debit=float(smetkoplan_obj[key].n_debit+smetkoplan_obj[key].debit-smetkoplan_obj[key].n_kredit-smetkoplan_obj[key].kredit)
                        smetkoplan_obj[key].s_kredit=0
                    elif (smetkoplan_obj[key].n_kredit+smetkoplan_obj[key].kredit)-(smetkoplan_obj[key].n_debit+smetkoplan_obj[key].debit)>0:
                        smetkoplan_obj[key].s_debit=0
                        smetkoplan_obj[key].s_kredit=float(smetkoplan_obj[key].n_kredit+smetkoplan_obj[key].kredit-smetkoplan_obj[key].n_debit-smetkoplan_obj[key].debit)





#                    smetkoplan_obj[key].s_kredit+=float(row.suma)
#                if smetkoplan_obj[key].s_debit>smetkoplan_obj[key].s_kredit: #
#                    smetkoplan_obj[key].s_debit=smetkoplan_obj[key].s_debit-smetkoplan_obj[key].s_kredit
#                    smetkoplan_obj[key].s_kredit=0
#                elif smetkoplan_obj[key].s_debit<smetkoplan_obj[key].s_kredit: #
#                    smetkoplan_obj[key].s_debit=0
#                    smetkoplan_obj[key].s_kredit=smetkoplan_obj[key].s_kredit-smetkoplan_obj[key].s_debit
    

def index(request):
       
    return render(request, 'base.html')

def oschetovodiavane_pokupki(opisanie,opisanie2):
    stoki_list=['храни','храна','консум','пиво','плод','зелен','сток','пром','цигари','хляб','хлебни','брашн','зърнен','тест. изд.','риба','разни','месо','месни','мляко','млечни','кашк','л-ца','подправ','бира','безалк','напитк','захарн','зах.','кафе','ст.дом','промишлен','препара','прах','тестен','закус','ядки','боза','сладолед','чай','пампер','детск','мин.','пюре']
    uslugi_list=['сервиз','услуг','охрана','обслужване','абонам','ремонт','ремнот']
    elektrichestvo=['електричество','ток','енергия']
    lizing=['лизинг','лизингова']
    materiali_remont=['дървев мат', 'стр.','строителни']
    ch_string=opisanie
    contr_string=opisanie2
    list_smetki=[]
 
    if any(ele in ch_string for ele in stoki_list):#oschetovodiavane na zakupuvane na stoki
        smetka1_dt=304
 #           list_smetki.append(smetka1_dt)
        smetka1_kt=501
 #           list_smetki.append(smetka2_kt)
        smetka2_dt=4531
 #           list_smetki.append(smetka2_dt)
        smetka2_kt=501
 #           list_smetki.append(smetka2_kt)
        list_smetki=[smetka1_dt,smetka1_kt,smetka2_dt,smetka2_kt]

    elif any(ele in ch_string for ele in uslugi_list):#oschetovodiavane na zakupuvane na uslugi
        smetka1_dt=602
        smetka1_kt=501
        smetka2_dt=4531
        smetka2_kt=501
        list_smetki=[smetka1_dt,smetka1_kt,smetka2_dt,smetka2_kt]

    elif any(ele in ch_string for ele in materiali_remont):#oschetovodiavane na zakupuvane na uslugi
        smetka1_dt=601
        smetka1_kt=501
        smetka2_dt=4531
        smetka2_kt=501
        list_smetki=[smetka1_dt,smetka1_kt,smetka2_dt,smetka2_kt]

    elif any(ele in ch_string for ele in elektrichestvo):#oschetovodiavane na zakupuvane na el.tok 6021
        smetka1_dt=6021
        smetka1_kt=501
        smetka2_dt=4531
        smetka2_kt=501
        smetka3_dt=0
        smetka3_kt=0
        smetka4_dt=0
        smetka4_kt=0
        list_smetki=[smetka1_dt,smetka1_kt,smetka2_dt,smetka2_kt]

    elif ch_string=='вода':#oschetovodiavane na zakupuvane na voda 6022
        smetka1_dt=6022
        smetka1_kt=501
        smetka2_dt=4531
        smetka2_kt=501
        smetka3_dt=0
        smetka3_kt=0
        smetka4_dt=0
        smetka4_kt=0
        list_smetki.append(smetka1_dt,smetka1_kt,smetka2_dt,smetka2_kt)


    elif ch_string=='наем' and contr_string=='BG000573078':#oschetovodiavane na naem RPK Balkan 6023
        smetka1_dt=6023
        smetka1_kt=501
        smetka2_dt=4531
        smetka2_kt=501
        smetka3_dt=0
        smetka3_kt=0
        smetka4_dt=0
        smetka4_kt=0
        list_smetki=[smetka1_dt,smetka1_kt,smetka2_dt,smetka2_kt]

    elif ch_string=='наем' and contr_string!='BG000573078':#oschetovodiavane na naem 6023
        smetka1_dt=6023
        smetka1_kt=4012
        smetka2_dt=4531
        smetka2_kt=4012
        smetka3_dt=0
        smetka3_kt=0
        smetka4_dt=0
        smetka4_kt=0
        list_smetki=[smetka1_dt,smetka1_kt,smetka2_dt,smetka2_kt]

    elif ch_string=='гориво':#oschetovodiavane na zakupuvane na gorivo 302
        smetka1_dt=302
        smetka1_kt=501
        smetka2_dt=4531
        smetka2_kt=501
        smetka3_dt=0
        smetka3_kt=0
        smetka4_dt=0
        smetka4_kt=0
        list_smetki=[smetka1_dt,smetka1_kt,smetka2_dt,smetka2_kt]

    elif any(ele in ch_string for ele in lizing):#oschetovodiavane na вноска лизинг
        smetka1_dt=159
        smetka1_kt=4011
        smetka2_dt=6212
        smetka2_kt=625
        smetka3_dt=4531
        smetka3_kt=4011
        smetka4_dt=159
        smetka4_kt=4011
        list_smetki=[smetka1_dt,smetka1_kt,smetka2_dt,smetka2_kt,smetka3_dt,smetka3_kt,smetka4_dt,smetka4_kt]
        
    else:
        smetka1_dt=0
        smetka1_kt=0
        smetka2_dt=0
        smetka2_kt=0
        smetka3_dt=0
        smetka3_kt=0
        smetka4_dt=0
        smetka4_kt=0
        list_smetki=[smetka1_dt,smetka1_kt,smetka2_dt,smetka2_kt]
    return list_smetki
            
def oborotna_vedomost(request):
    smetki=smetkoplan.objects.all()
    ved=vedomost.objects.all()
    smetkoplan_obj={}
#за всяка сметка от таблицата сметкоплан се създава елемент от речника smetkoplan_obj    
    for smetka in smetki:
        smetkoplan_obj[smetka.smetka]=Sm(smetka.smetka,smetka.opisanie,smetka.n_saldo_dt,smetka.n_saldo_kt,0,0)

#тук функцията smetkoplan_analiz  
    smetkoplan_analiz(ved, smetkoplan_obj)

    
    return render(request, 'catalog.html',{'smetkoplan_obj':smetkoplan_obj})


def upload_file_prodajbi(request):
    file_content = None
    form = UploadFileForm()
    listi_file=[]
    lines=[]
    lines1=[]

            
        
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = request.FILES['file'] # When a user uploads a text-based file (like CSV), Django gives you a File object in request.FILES.
                                                  # Here uploaded_file is a binary file object - opened file.
                                                  # request.FILES will only contain data if the request method was POST, at least one file field was actually posted,
                                                  # and the <form> that posted the request has the attribute enctype="multipart/form-data". Otherwise, request.FILES
                                                  # will be empty
            file_content = uploaded_file.read().decode('windows-1251')#file_content is a string representation of the binary file object - uploaded_file
            lines = file_content.splitlines() # splitlines () method splits a string into a list. The splitting is done at line breaks.

            for row in lines:
                try:
                    buls=row[0:11].strip()
                    first_f=row[11:21].strip()
                    aparat=row[21:42].strip()
                    nomer=row[42:44].strip()
                    date=row[44:72].strip()
                    firma='Kalina'
                    opisanie=row[72:149].strip()
                    suma1=row[149:182].strip()
                    suma2=row[182:197].strip()

schetovodstvo/templates/base.html
{% load static %}

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>index.html</title>


</head>

<body class="body_centered_1">
<div class="container_1_1">
<P>Hi there this is the new SCHETOVODSTVO page</P>
<table>
<tr>
<td><a href="{% url 'schetovodstvo:upload_file_prodajbi'%}">Качване на файл - продажби</a></td>
<td><a href="{% url 'schetovodstvo:upload_file_pokupki'%}">Качване на файл - покупки</a></td>
<td><a href="{% url 'schetovodstvo:upload_file_zaplati'%}">Качване на файл - заплати</a></td>
<td><a href="{% url 'schetovodstvo:upload_file_bank'%}">Качване на файл - банка</a></td>
</tr>
</table>

<P><a href="{% url 'schetovodstvo:oborotna_vedomost'%}">Оборотна ведомост</a></P>
<P></P>
<P></P>
<P></P>
<P></P>
<P><a href="{% url 'schetovodstvo:function_display'%}">Филтриране по критерии</a></P>
</div>

<div class="main_1_1_3">
	<div>

	</div> 
	
	
               


	<div>
		
                {% block content %}
                {% endblock %}
                

		
	</div>
	
        

</div>


	
</body>
</html>

schetovodstvo/templates/catalog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<P>This is the VEDOMOST</P>
<table border=1 cellpadding=2>


{% for value in smetkoplan_obj.values %}
{% if value.s_debit|add:value.s_kredit > 0%}
<tr>
<td>{{value.smetka }}</td>
<td>{{value.s_ime}}</td>
<td>{{value.n_debit|floatformat:2 }}</td>
<td>{{value.n_kredit|floatformat:2 }}</td>
<td>{{value.debit|floatformat:2 }}</td>
<td>{{value.kredit|floatformat:2 }}</td>
<td>{{value.s_debit|floatformat:2 }}</td>
<td>{{value.s_kredit|floatformat:2 }}</td>
</tr>
{% endif %}
{% endfor %}
</table>





{% endblock content %}

schetovodstvo/templates/display.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<P>This is the DISPLAY</P>

<form method="get">
<!--{% csrf_token %}-->
  {{ form_criterii.as_p }}
  <button type="submit">Filter</button>
</form>


{% if x %}
<p>{{xx}}</p>
<p>{{x}}</p>
{% endif %}


<!--
<table border=1>
{% if zaiavka != None %}
{% for row in zaiavka %}
        <tr>
          <td>{{ row.doc }}</td>
          <td>{{ row.suma }}</td>
          <td>{{ row.debit }}</td>
          <td>{{ row.credit }}</td>
        </tr>
{% endfor %}
{% endif %}
</table>
-->
{% if formset != None %}
<p>FORM</p>
  <form method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    <table>
      <thead>
        <tr>
          <th>month-202501</th><th>document</th><th>date</th><th>firma</th><th>opisanie</th><th>suma</th><th>debit</th><th>credit</th>
        </tr>
      </thead>
      <tbody>
        {% for form in formset %}
          <tr>
          {{ form.id }}
            <td>{{ form.first_f }}</td>
            <td>{{ form.doc }}</td>
            <td>{{ form.date }}</td>
            <td>{{ form.firma }}</td>
            <td>{{ form.opisanie }}</td>
            <td>{{ form.suma }}</td>            
            <td>{{ form.debit }}</td>            
            <td>{{ form.credit }}</td> 
            <td>{{ form.DELETE }}</td>            
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <button type="submit">Save Changes</button>
  </form>
{% endif %}
<!--
<table border=1 cellpadding=2>
{% for value in smetkoplan_obj.values %}
{% if value.s_debit|add:value.s_kredit > 0%}
<tr>
<td>{{value.smetka }}</td>
<td>{{value.s_ime}}</td>
<td>{{value.n_debit|floatformat:2 }}</td>
<td>{{value.n_kredit|floatformat:2 }}</td>
<td>{{value.debit|floatformat:2 }}</td>
<td>{{value.kredit|floatformat:2 }}</td>
<td>{{value.s_debit|floatformat:2 }}</td>
<td>{{value.s_kredit|floatformat:2 }}</td>
</tr>
{% endif %}
{% endfor %}
</table>
-->




{% endblock content %}

schetovodstvo/templates/upload.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<P>This is the UPLOAD form</P>
<h2>Upload a file</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
 
{% if lines1 %}
        <h3>File Contents:</h3>
        <pre>{{ lines1 }}</pre>
{% endif %}

{% endblock content %}

schetovodstvo/templates/upload_bank.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<P>This is the UPLOAD form</P>
<h2>Upload a file</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
 
{% if lines1 %}
        <h3>File Contents:</h3>
        {% for row in lines1%}
        <pre>{{ row }}</pre>
        {% endfor %}
{% endif %}

{% endblock content %}

schetovodstvo/templates/upload_pok.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<P>This is the UPLOAD form</P>
<h2>Upload a file</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
 
{% if lines1 %}
        <h3>File Contents:</h3>
        <pre>{{ lines1 }}</pre>
{% endif %}

{% endblock content %}

schetovodstvo/templates/upload_zaplati.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<P>This is the UPLOAD form</P>
<h2>Upload a file</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
 
{% if lines1 %}
        <h3>File Contents:</h3>
        <pre>{{ lines1 }}</pre>
{% endif %}

{% endblock content %}